buffer_size: 15000
total_timesteps: 1000000
gamma: 0.8
eps_start: 1.0
eps_end: 0.05
tau: 1.0
batch_size: 1024
lr: 5.e-5
learning_starts: 1000
train_frequency: 256
exploration_fraction: 0.1
target_network_frequency: 10
gradient_steps: 128
validation_interval: 2000
validation_episodes: 10
max_frames_per_val_episode: 1000
num_repeat_exp: 1